### ISSUE TITLE
"ask" works, "always" not.

### ISSUE THREAD

**Issue by Chazy12** [ArtificalSUN/MKS-WIFI_PS_uploader#1]
As the title, of you out "ask" on the post process, it works like a charm. If you put "always", it will not working.

**Comment by ArtificalSUN** [comment]
Fixed by adding 3 second delay between uploading g-code and starting a print-job. Apparently, Wi-Fi module firmware need some "window" after upload is finished to go back to normal operation and properly handle job start commands.
