### ISSUE TITLE
Linux Version?

### ISSUE THREAD

**Issue by Chazy12** [ArtificalSUN/MKS-WIFI_PS_uploader#2]
could be possible to have a linux (ubuntu) version?
thanks a lot.

**Comment by ArtificalSUN** [comment]
Well, technically Python version is multiplatform and you can run it on any system as long as you have Python 3 (and requests package) installed. However, I'll try to figure out how to build executables for linux (I'll have to install linux for that, apparently)

**Comment by yorik** [comment]
Just put `python3 /<path>/MKS-WIFI_PS_uploader/MKS_WIFI_PS_upload.pyw <ip> ask;` into Post-processing scripts.

It works just fine on debian, I think I had to install only `python3-tk` package. There is no need to create an executable for linux.

BTW, thank you so much for the uploader!
