### ISSUE TITLE
Not working after the prusaslicer 2.3 update.

### ISSUE THREAD

**Issue by Chazy12** [ArtificalSUN/MKS-WIFI_PS_uploader#3]
Hello.
In the previous version of prusaslicer/SuperSlicer works perfectly!
After the update to 2.3, the script upload to the printer, but not print. Watched inside the sdcard too, but there's not the file uploaded there.

**Comment by ArtificalSUN** [comment]
Does the printer itself display the upload process? Do you get any errors in prusaslicer? Which method do you use to run the script - python or exe?
I don't have the printer anymore so I can't test it myself.

**Comment by ArtificalSUN** [comment]
I asked around and no one else has problems with PS or SS v.2.3. Since there is no new information on this matter I'm closing this issue.
