### ISSUE TITLE
Model preview as in MKS Wi-Fi plugin for cura?

### ISSUE THREAD

**Issue by Malderin** [ArtificalSUN/MKS-WIFI_PS_uploader#4]
Is it possible to view the model as implemented in MKS Wi-Fi plugin for cura?
![1](https://user-images.githubusercontent.com/52313714/128615452-f9c07349-d692-406d-a251-e8f502a5c3f2.jpg)
![2](https://user-images.githubusercontent.com/52313714/128615453-e6efabf0-5f9e-4bd3-8bc8-818793f1787d.jpg)

Cura plugin:
https://github.com/Jeredian/mks-wifi-plugin

**Comment by Ciizel** [comment]
+1

**Comment by SH1NZ33** [comment]
See my fork, it works by converting Prusa thumbnails into TFT thumbnails

**Comment by ArtificalSUN** [comment]
Thx @SH1NZ33, I've merged your changes. Better late than never, I guess.
