### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by saloid** [ArtificalSUN/MKS-WIFI_PS_uploader#6]
I'm getting upload error at the same place, right after uploading start. I tried both .exe and .pyw versions. What could be wrong?
![image](https://user-images.githubusercontent.com/22222390/147405349-5d40bca8-e620-44ae-a294-1a9883b39109.png)
![image](https://user-images.githubusercontent.com/22222390/147405375-4867ac49-c6cf-4c7b-a4e4-cac89fb65742.png)

**Comment by RazorRunner** [comment]
For someone who will face it in future. Please make sure that there are no other program trying to connect to the printer. 
For me the problem was in Ultimaker Cura that was open side by side with the Prusaslicer that was trying to connect to printer in a background and interrupting the upload.
